name: Pulumi Debug Workflow

on:
  workflow_dispatch: 

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print huidige directory en inhoud
        working-directory: deployment
        run: |
          echo "Huidige werkdirectory:"
          pwd
          echo "Inhoud van de repository:"
          ls -la
          echo "Volledige directory-structuur:"
          sudo apt-get install tree -y
          tree -L 3

      - name: Controleer of Pulumi is geïnstalleerd
        run: |
          echo "Pulumi versie:"
          pulumi version || echo "Pulumi is niet geïnstalleerd"

      - name: Controleer of Pulumi.yaml aanwezig is in /deployment
        run: |
          if [ -f deployment/Pulumi.yaml ]; then
            echo "Pulumi.yaml gevonden in deployment/"
            cat deployment/Pulumi.yaml
          else
            echo "Pulumi.yaml niet gevonden in deployment/"
          fi

      - name: Controleer Pulumi stack
        run: |
            echo "Beschikbare Pulumi stacks:"
            pulumi stack ls --cwd=deployment || echo "Geen stacks gevonden of Pulumi is niet correct geconfigureerd"
        env:
            PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}


      - name: Controleer Pulumi project
        run: |
          echo "Pulumi projectinformatie:"
          pulumi project --cwd=deployment || echo "Pulumi project kon niet worden geladen"
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Controleer Node.js installatie
        run: |
          echo "Node.js versie:"
          node -v || echo "Node.js is niet geïnstalleerd"

      - name: Controleer /deployment directory en inhoud
        run: |
          if [ -d deployment ]; then
            echo "'deployment/' directory gevonden"
            ls -la deployment
          else
            echo "'deployment/' directory niet gevonden"
          fi

