name: Deploy to AWS with Pulumi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: deployment

      - name: Install missing Pulumi dependencies (indien nodig)
        run: npm install @pulumi/pulumiservice
        continue-on-error: true  # Voorkomt falen als het al geïnstalleerd is
        working-directory: deployment

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          
      - name: Force AWS Credentials (Disable Profile)
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_REGION=eu-central-1" >> $GITHUB_ENV
          echo "AWS_PROFILE=" >> $GITHUB_ENV 
        working-directory: deployment

      - name: Install Pulumi CLI
        uses: pulumi/actions@v4
        with:
          pulumi-version: latest
        working-directory: deployment

      - name: Verify Pulumi Plugins
        run: pulumi plugin install resource aws $(pulumi plugin ls | grep aws | awk '{print $2}')
        working-directory: deployment

      - name: Set Pulumi Access Token
        run: echo "PULUMI_ACCESS_TOKEN=${{ secrets.PULUMI_ACCESS_TOKEN }}" >> $GITHUB_ENV
        working-directory: deployment

      - name: Verify Pulumi Login
        run: pulumi whoami
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        working-directory: deployment

      - name: Select Pulumi Stack
        run: pulumi stack select dev
        working-directory: deployment
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Run Pulumi
        uses: pulumi/actions@v4
        with:
          command: up
          stack-name: dev
        working-directory: deployment
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

